### ISSUE TITLE
code: Complete rewrite

### ISSUE THREAD

**Issue by mikayelgr** [polygon-isecure/stormi#3]
This project is not where I wanted it to be. There are some decisions that I regret making and think that it will be a better option to rewrite the entire project again instead of building on an unstable foundation. I am going to post all updates in this issue.

**Comment by ejcheng** [comment]
@michaelgrigoryan25 If you decide to proceed with this route, I can help you build the UI and front-end.

**Comment by mikayelgr** [comment]
@import-brain To be frank, this project is not supposed to have a custom frontend. I think most of the people would prefer connecting stormi to Grafana and Prometheus, to monitor the performance. But thanks for the willingness to help! I appreciate it a lot!

**Comment by ejcheng** [comment]
> @import-brain To be frank, this project is not supposed to have a custom frontend. I think most of the people would prefer connecting stormi to Grafana and Prometheus, to monitor the performance. But thanks for the willingness to help! I appreciate it a lot!

Ah I see! Thanks!
